CREATE TYPE public.order_status AS ENUM ('new','confirmed','shipped','delivered','cancelled');
CREATE TYPE public.app_role AS ENUM ('admin','user');

CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can read own roles" ON public.user_roles FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role);
$$;

CREATE TABLE public.orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  order_number bigint GENERATED BY DEFAULT AS IDENTITY,
  customer_name text NOT NULL,
  email text,
  phone text NOT NULL,
  address text NOT NULL,
  city text NOT NULL,
  area text NOT NULL,
  postal_code text NOT NULL,
  country text NOT NULL DEFAULT 'Bangladesh',
  design_id text NOT NULL,
  design_name text NOT NULL,
  thickness text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  delivery_area text NOT NULL,
  unit_price integer NOT NULL,
  delivery_fee integer NOT NULL,
  total integer NOT NULL,
  status public.order_status NOT NULL DEFAULT 'new',
  note text
);

GRANT INSERT ON public.orders TO anon, authenticated;
GRANT SELECT, UPDATE, DELETE ON public.orders TO authenticated;
GRANT ALL ON public.orders TO service_role;

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can place an order" ON public.orders FOR INSERT TO anon, authenticated WITH CHECK (
  char_length(customer_name) BETWEEN 1 AND 120
  AND phone ~ '^\+8801[3-9][0-9]{8}$'
  AND char_length(address) BETWEEN 1 AND 400
  AND thickness IN ('4mm','5mm')
  AND quantity BETWEEN 1 AND 5
  AND delivery_area IN ('dhaka','outside')
  AND status = 'new'
);
CREATE POLICY "Admins can read orders" ON public.orders FOR SELECT TO authenticated USING (public.has_role(auth.uid(),'admin'));
CREATE POLICY "Admins can update orders" ON public.orders FOR UPDATE TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE POLICY "Admins can delete orders" ON public.orders FOR DELETE TO authenticated USING (public.has_role(auth.uid(),'admin'));

CREATE INDEX orders_created_at_idx ON public.orders (created_at DESC);